name: CI/CD Pipeline for ABC Web App
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Clean, Test and Build ABC Web App in CICD Pipeline
      - name: Clean, Test & Build ABC Web App in CICD Pipeline
        run: mvn clean test install

      # Upload Maven build output as artifact
      - name: Upload Maven build output
        uses: actions/upload-artifact@v4
        with:
          name: maven-build-output
          path: target/

      # Run DAST scan using OWASP ZAP in CICD Pipeline
      - name: DAST Scan using OWASP ZAP
        run: |
          sudo apt-get update
          sudo apt-get -y install wget
          sudo apt-get -y install default-jdk
          wget https://github.com/zaproxy/zaproxy/releases/download/v2.16.0/ZAP_2.16.0_Linux.tar.gz
          tar -xvf ZAP_2.16.0_Linux.tar.gz
          cd ZAP_2.16.0
          ./zap.sh -cmd -quickurl https://www.example.com -quickprogress -quickout ../zap_report.html

      # Upload OWASP ZAP scan output as artifact
      - name: Upload OWASP ZAP scan output
        uses: actions/upload-artifact@v4
        with:
          name: owasp-zap-output
          path: ZAP_2.16.0/zap_report.html