name: CI/CD Pipeline for ABC Web App
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Clean, Test and Build ABC Web App in CICD Pipeline
      - name: Clean, Test & Build ABC Web App in CICD Pipeline
        run: mvn clean test install

      # Upload Maven build output as artifact
      - name: Upload Maven build output
        uses: actions/upload-artifact@v4
        with:
          name: maven-build-output
          path: target/

      # Build Docker image
      - name: Build Docker image
        run: |
              docker build -t ${{ secrets.DOCKER_USERNAME }}/abc-corp-docker-img:${{ github.sha }} -f ./Dockerfile .
              docker save ${{ secrets.DOCKER_USERNAME }}/abc-corp-docker-img:${{ github.sha }} -o docker_image_${{ github.sha }}.tar
      # Upload Docker build output as artifact
      - name: Upload Docker build output
        uses: actions/upload-artifact@v4
        with:
          name: docker-build-output
          path: docker_image_${{ github.sha }}.tar

      # Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
           echo "${{ secrets.DOCKER_PAT }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
           docker push ${{ secrets.DOCKER_USERNAME }}/abc-corp-docker-img:${{ github.sha }}
      # Run DAST scan using OWASP ZAP in CICD Pipeline
      - name: DAST Scan using OWASP ZAP
        run: |
          sudo apt-get update
          sudo apt-get -y install wget
          sudo apt-get -y install default-jdk
          wget https://github.com/zaproxy/zaproxy/releases/download/v2.16.0/ZAP_2.16.0_Linux.tar.gz
          tar -xvf ZAP_2.16.0_Linux.tar.gz
          cd ZAP_2.16.0
          ./zap.sh -cmd -quickurl https://www.example.com -quickprogress 
      #  ./zap.sh -cmd -quickurl https://www.example.com -quickprogress -quickout ../zap_report.html

      # Upload OWASP ZAP scan output as artifact
      - name: Upload OWASP ZAP scan output
        uses: actions/upload-artifact@v4
        with:
          name: owasp-zap-output
          path: ZAP_2.16.0/
