name: CI/CD Pipeline for ABC Web App
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Clean, Test and Build ABC Web App in CICD Pipeline
      - name: Clean, Test & Build ABC Web App in CICD Pipeline
        run: mvn clean test install

      # Run DAST scan using OWASP ZAP in CICD Pipeline
      - name: DAST Scan using OWASP ZAP
        run: |
          sudo apt-get update
          sudo apt-get -y install wget
          sudo apt-get -y install default-jdk
          wget https://github.com/zaproxy/zaproxy/releases/download/v2.14.0/ZAP_2.14.0_Linux.tar.gz
          tar -xvf ZAP_2.14.0_Linux.tar.gz
          cd ZAP_2.14.0
          ./zap.sh -cmd -quickurl https://www.example.com -quickprogress